; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Rhinoloader"
#define MyAppVersion "3.3"
#define MyAppPublisher "Rhino Cheats"
#define MyAppURL "www.rhinocheats.com"  
#define MyAppCopyright "Copyright © 2k19"
#define MyAppExeName "Rhinoloader.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{936DB3CB-9D10-44DC-8FB3-A3E1431C5D40}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright={#MyAppCopyright}
VersionInfoVersion={#MyAppVersion}
DefaultDirName=C:\RC
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputDir=D:\rhinocheats\source\repos\RhinoCheats_Setup
OutputBaseFilename=Rhinosetup
SetupIconFile=D:\rhinocheats\source\repos\RhinoCheats_Setup\Rhinoloader.ico
UninstallDisplayIcon=D:\rhinocheats\source\repos\RhinoCheats_Setup\Rhinoloader.ico  
WizardSmallImageFile=D:\rhinocheats\source\repos\RhinoCheats_Setup\Rhinoloader.bmp
WizardImageAlphaFormat=defined
Password=QEWHTjNAPvU=MkV3RE6C#ARNjT9n32@JP%csp^ar=NYe5$pgbQh&k^WQvW_ehy!vp*8myJ
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\Rhinoloader.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\Sounds\activated.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\Sounds\assist.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\Sounds\dominating.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\doublekill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\excellent.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\firstblood.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\godlike.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\headshot.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\holyshit.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\humiliation.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\impressive.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\killingspree.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\ludicrouskill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\menu.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\menu_toggle.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\monsterkill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\multikill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\rampage.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\StarT.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\tripplekill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\ultrakill.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\unstoppable.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\wickedsick.wav"; DestDir: "{app}\Sounds"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\laughts\demoman_laughlong02.wav"; DestDir: "{app}\Sounds\laughts"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\laughts\medic_laughlong02.wav"; DestDir: "{app}\Sounds\laughts"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\laughts\scout_laughlong02.wav"; DestDir: "{app}\Sounds\laughts"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\laughts\sniper_laughlong02.wav"; DestDir: "{app}\Sounds\laughts"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Sounds\laughts\spy_laughlong01.wav"; DestDir: "{app}\Sounds\laughts"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Textures\texture-1.png"; DestDir: "{app}\Textures"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Textures\texture-2.png"; DestDir: "{app}\Textures"; Flags: ignoreversion
Source: "D:\rhinocheats\source\repos\RhinoCheats_Setup\\Textures\texture-map.png"; DestDir: "{app}\Textures"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

